name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bussapp_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/bussapp_test
      SESSION_SECRET: test_secret_key_for_testing_purposes_only_1234567890123456
      NEXT_TELEMETRY_DISABLED: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Prepare database schema
        run: |
          psql "$DATABASE_URL" -f migrations/001_initial_schema.sql
          psql "$DATABASE_URL" -f migrations/002_add_bank_account_to_organizations.sql

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration

      - name: Build production bundle
        run: npm run build

      - name: Run end-to-end smoke tests
        env:
          PLAYWRIGHT_BASE_URL: http://127.0.0.1:3000
        run: |
          PORT=3000 npm run start &
          npx wait-on http://127.0.0.1:3000/login
          npm run test:e2e
